apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workflow-nexus-pvc
  labels:
    app: workflow-nexus
    platform: starbridge
    mode: developer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path