apiVersion: v1
kind: Service
metadata:
  name: ollama-MODEL_NAME
  labels:
    app: ollama
    model: MODEL_NAME
    component: ai-service
spec:
  type: ClusterIP
  ports:
  - port: 11434
    targetPort: 11434
    protocol: TCP
    name: http
  selector:
    app: ollama
    model: MODEL_NAME