apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  # Default password: "postgres123" (base64 encoded)
  # You can change this by running: echo -n "your-password" | base64
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM=